"""Claude per-CLI adapter emission.

Produces:
    generated/CLAUDE.md
    generated/claude/settings.json
    generated/claude/hooks/pre_tool_use.py
    generated/claude/hooks/pre_file_write.py
    generated/claude/hooks/session_start.py
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Mapping

from agentos_cli.core.policy import Policies

CLI_NAME = "claude"


# ----------------- Hook script template (Claude flavor) ----------------- #
# Claude: blocks tool calls when hook exits with code 2.
# Reads JSON event from stdin (a tool-use request) and decides.
_HOOK_TEMPLATE = '''\
#!/usr/bin/env python3
"""GENERATED BY agentic-os adapter compiler — do not edit by hand.

CLI: claude
Event: {event}
Matcher: {matcher}

Reads JSON from stdin describing the tool invocation. Evaluates against
policies under agent-os/policies/. Fail-closed: on any error → deny (exit 2).
"""
from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path

DENY_EXIT = 2
ALLOW_EXIT = 0
MAX_STDIN_BYTES = 1_000_000  # 1MB cap


def _audit(decision: str, reason: str, raw_len: int) -> None:
    try:
        root = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
        outdir = Path(root) / "agent-os" / "outputs" / "_global" / "temp"
        outdir.mkdir(parents=True, exist_ok=True)
        path = outdir / "hook-audit.jsonl"
        rec = {{
            "ts": time.time(),
            "cli": "claude",
            "event": {event!r},
            "decision": decision,
            "reason": reason,
            "input_bytes": raw_len,
        }}
        with path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(rec) + "\\n")
    except Exception:
        # Auditing must never raise.
        pass


def _deny(reason: str, raw_len: int = 0) -> int:
    payload = {{"decision": "deny", "reason": reason}}
    try:
        sys.stdout.write(json.dumps(payload))
        sys.stdout.flush()
    except Exception:
        pass
    _audit("deny", reason, raw_len)
    return DENY_EXIT


def _allow(reason: str, raw_len: int) -> int:
    _audit("allow", reason, raw_len)
    return ALLOW_EXIT


def _load_policies():
    try:
        root = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
        # Import lazily so the hook is robust even if package is uninstalled.
        sys.path.insert(0, str(Path(root)))
        from agentos_cli.core.policy import load_policies  # type: ignore
        return load_policies(Path(root) / "agent-os" / "policies")
    except Exception:
        return None


def _evaluate(payload: dict, policies) -> tuple[str, str]:
    if policies is None:
        return "deny", "policy load failure (fail-closed)"
    tool = payload.get("tool_name") or payload.get("tool") or ""
    tinput = payload.get("tool_input") or payload.get("input") or {{}}
    if not isinstance(tinput, dict):
        return "deny", "tool_input is not an object"
    # Bash → evaluate command string
    if tool == "Bash":
        from agentos_cli.safety.shell_parse import parse_shell_string  # type: ignore
        from agentos_cli.core.policy import evaluate_shell  # type: ignore
        cmd = tinput.get("command")
        if not isinstance(cmd, str):
            return "deny", "Bash command must be a string"
        argv = parse_shell_string(cmd)
        if argv is None:
            return "deny", "unsafe shell construct; route via approval"
        decision, rule = evaluate_shell(argv, policies)
        reason = (rule or {{}}).get("reason", "") if rule else ""
        if decision == "forbid":
            return "deny", f"shell forbid: {{reason}}"
        if decision == "prompt":
            return "deny", f"shell prompt (requires approval): {{reason}}"
        return "allow", "shell allow"
    # Write/Edit/MultiEdit → evaluate file path
    if tool in ("Write", "Edit", "MultiEdit"):
        from agentos_cli.core.policy import evaluate_file_write  # type: ignore
        path = tinput.get("file_path") or tinput.get("path")
        if not isinstance(path, str) or not path:
            return "deny", "file_path missing"
        root = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
        decision, reason = evaluate_file_write(Path(path), Path(root), policies)
        if decision == "deny":
            return "deny", f"file write denied: {{reason}}"
        return "allow", "file write allow"
    # Other tools (Read, Glob, etc.) — let through.
    return "allow", f"tool {{tool!r}} not policy-evaluated"


def main() -> int:
    raw_len = 0
    try:
        raw = sys.stdin.buffer.read(MAX_STDIN_BYTES + 1)
        raw_len = len(raw)
        if raw_len == 0:
            return _deny("empty stdin", raw_len)
        if raw_len > MAX_STDIN_BYTES:
            return _deny("stdin payload exceeds 1MB cap", raw_len)
        try:
            text = raw.decode("utf-8", errors="strict")
        except UnicodeDecodeError as e:
            return _deny(f"utf-8 decode failure: {{e.__class__.__name__}}", raw_len)
        try:
            payload = json.loads(text)
        except json.JSONDecodeError as e:
            return _deny(f"json parse failure: {{e.__class__.__name__}}", raw_len)
        if not isinstance(payload, dict):
            return _deny("payload must be a JSON object", raw_len)
        # Reject prototype-pollution-style keys defensively.
        if any(k in payload for k in ("__proto__", "constructor", "prototype")):
            return _deny("disallowed reserved key in payload", raw_len)
        policies = _load_policies()
        decision, reason = _evaluate(payload, policies)
        if decision == "deny":
            return _deny(reason, raw_len)
        return _allow(reason, raw_len)
    except Exception as e:
        return _deny(f"unexpected: {{e.__class__.__name__}}", raw_len)


if __name__ == "__main__":
    sys.exit(main())
'''


def _settings_json(adapter_cfg: Mapping) -> str:
    """Render a settings.json registering each hook.

    Claude hook-registration shape (current docs):
        {"hooks": {"<NativeEvent>": [{"matcher": "...", "hooks": [{"type":"command","command":"..."}]}]}}
    """
    grouped: dict[str, list[dict]] = {}
    hook_root = adapter_cfg.get("hook_root_env") or "${CLAUDE_PROJECT_DIR}"
    for h in adapter_cfg.get("hooks", []):
        native = h["native_event"]
        matcher = h.get("matcher", "")
        script = h["script"]
        cmd = (
            f"python3 {hook_root}/agent-os/generated/"
            f"{adapter_cfg['output_subdir']}/hooks/{script}"
        )
        grouped.setdefault(native, []).append(
            {
                "matcher": matcher,
                "hooks": [{"type": "command", "command": cmd}],
            }
        )
    # Sort by event name for determinism. Each event's matchers preserved as
    # listed in adapter yaml.
    body = {"hooks": {k: grouped[k] for k in sorted(grouped)}}
    return json.dumps(body, indent=2, sort_keys=True) + "\n"


def emit(
    out_root: Path,
    context_md: str,
    policies: Policies,
    adapter_cfg: Mapping,
) -> list[tuple[Path, bytes]]:
    """Return list of (path, bytes) tuples to write. Deterministic ordering."""
    files: list[tuple[Path, bytes]] = []

    # 1. Top-level CLAUDE.md
    files.append((out_root / adapter_cfg["context_filename"], context_md.encode("utf-8")))

    sub = out_root / adapter_cfg["output_subdir"]

    # 2. settings.json
    files.append(
        (sub / adapter_cfg["settings_filename"], _settings_json(adapter_cfg).encode("utf-8"))
    )

    # 3. hook scripts
    hooks_dir = sub / adapter_cfg["hooks_subdir"]
    seen: set[str] = set()
    for h in adapter_cfg.get("hooks", []):
        script = h["script"]
        if script in seen:
            continue
        seen.add(script)
        body = _HOOK_TEMPLATE.format(event=h["event"], matcher=h.get("matcher", ""))
        files.append((hooks_dir / script, body.encode("utf-8")))

    return files
