"""Codex per-CLI adapter emission.

Locked decision #8: enforcement is via execpolicy ``.rules`` (Starlark); hooks
are guardrails because Codex hook non-2 exits do not block.

Produces:
    generated/AGENTS.md
    generated/codex/config.toml
    generated/codex/hooks/tool_before.py
    generated/codex/rules/agentic-os.rules

Codex execpolicy syntax (verified against `codex execpolicy check`):
    prefix_rule(pattern=["git", "status"], decision="allow")
    prefix_rule(pattern=["rm", "-rf", "/"], decision="forbidden")
    prefix_rule(pattern=["git", "push"], decision="prompt")

Valid decisions: ``allow``, ``forbidden``, ``prompt`` (verified empirically;
other values cause Starlark parse failure).
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Mapping

from agentos_cli.core.policy import Policies

CLI_NAME = "codex"

# Map our policy decision names to Codex execpolicy DSL decisions.
_DECISION_MAP = {
    "forbid": "forbidden",
    "prompt": "prompt",
    "allow": "allow",
}


_HOOK_TEMPLATE = '''\
#!/usr/bin/env python3
"""GENERATED BY agentic-os adapter compiler — do not edit by hand.

CLI: codex
Event: {event}

Codex enforcement is execpolicy `.rules`; this hook is a guardrail.
Returns JSON decision on stdout. Exits 2 on deny (note: Codex does not always
honor a non-zero hook exit as a hard block — rules are the source of truth).
"""
from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path

DENY_EXIT = 2
ALLOW_EXIT = 0
MAX_STDIN_BYTES = 1_000_000


def _audit(decision: str, reason: str, raw_len: int) -> None:
    try:
        root = os.environ.get("CODEX_PROJECT_DIR") or os.getcwd()
        outdir = Path(root) / "agent-os" / "outputs" / "_global" / "temp"
        outdir.mkdir(parents=True, exist_ok=True)
        path = outdir / "hook-audit.jsonl"
        rec = {{
            "ts": time.time(),
            "cli": "codex",
            "event": {event!r},
            "decision": decision,
            "reason": reason,
            "input_bytes": raw_len,
        }}
        with path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(rec) + "\\n")
    except Exception:
        pass


def _deny(reason: str, raw_len: int = 0) -> int:
    try:
        sys.stdout.write(json.dumps({{"decision": "deny", "reason": reason}}))
        sys.stdout.flush()
    except Exception:
        pass
    _audit("deny", reason, raw_len)
    return DENY_EXIT


def _allow(reason: str, raw_len: int) -> int:
    _audit("allow", reason, raw_len)
    return ALLOW_EXIT


def _load_policies():
    try:
        root = os.environ.get("CODEX_PROJECT_DIR") or os.getcwd()
        sys.path.insert(0, str(Path(root)))
        from agentos_cli.core.policy import load_policies  # type: ignore
        return load_policies(Path(root) / "agent-os" / "policies")
    except Exception:
        return None


def _evaluate(payload: dict, policies) -> tuple[str, str]:
    if policies is None:
        return "deny", "policy load failure (fail-closed)"
    argv = payload.get("argv") or payload.get("command") or []
    if isinstance(argv, str):
        from agentos_cli.safety.shell_parse import parse_shell_string  # type: ignore
        parsed = parse_shell_string(argv)
        if parsed is None:
            return "deny", "unsafe shell construct"
        argv = parsed
    if not isinstance(argv, list) or not all(isinstance(t, str) for t in argv):
        return "deny", "argv must be list[str]"
    from agentos_cli.core.policy import evaluate_shell  # type: ignore
    decision, rule = evaluate_shell(argv, policies)
    reason = (rule or {{}}).get("reason", "") if rule else ""
    if decision == "forbid":
        return "deny", f"shell forbid: {{reason}}"
    if decision == "prompt":
        return "deny", f"shell prompt (requires approval): {{reason}}"
    return "allow", "shell allow"


def main() -> int:
    raw_len = 0
    try:
        raw = sys.stdin.buffer.read(MAX_STDIN_BYTES + 1)
        raw_len = len(raw)
        if raw_len == 0:
            return _deny("empty stdin", raw_len)
        if raw_len > MAX_STDIN_BYTES:
            return _deny("stdin payload exceeds 1MB cap", raw_len)
        try:
            text = raw.decode("utf-8", errors="strict")
        except UnicodeDecodeError as e:
            return _deny(f"utf-8 decode failure: {{e.__class__.__name__}}", raw_len)
        try:
            payload = json.loads(text)
        except json.JSONDecodeError as e:
            return _deny(f"json parse failure: {{e.__class__.__name__}}", raw_len)
        if not isinstance(payload, dict):
            return _deny("payload must be a JSON object", raw_len)
        if any(k in payload for k in ("__proto__", "constructor", "prototype")):
            return _deny("disallowed reserved key in payload", raw_len)
        policies = _load_policies()
        decision, reason = _evaluate(payload, policies)
        if decision == "deny":
            return _deny(reason, raw_len)
        return _allow(reason, raw_len)
    except Exception as e:
        return _deny(f"unexpected: {{e.__class__.__name__}}", raw_len)


if __name__ == "__main__":
    sys.exit(main())
'''


def _config_toml(adapter_cfg: Mapping) -> str:
    """Minimal Codex config.toml registering hooks + execpolicy rules path."""
    lines: list[str] = []
    lines.append("# GENERATED BY agentic-os adapter compiler — do not edit by hand.")
    lines.append("")
    lines.append("[hooks]")
    # Sort by native event for determinism.
    hooks = sorted(adapter_cfg.get("hooks", []), key=lambda h: h["native_event"])
    for h in hooks:
        cmd = f"python3 ./.codex/hooks/{h['script']}"
        lines.append(f'"{h["native_event"]}" = "{cmd}"')
    lines.append("")
    lines.append("[execpolicy]")
    lines.append(
        f'rules = "./.codex/rules/{adapter_cfg["rules_filename"]}"'
    )
    return "\n".join(lines) + "\n"


def _format_argv_literal(argv: list[str]) -> str:
    """Render argv as a Starlark list literal using json.dumps (safe escaping)."""
    return "[" + ", ".join(json.dumps(t, ensure_ascii=False) for t in argv) + "]"


def _rules_file(policies: Policies) -> str:
    """Render the execpolicy .rules file from shell-policy.yaml.

    Order: forbidden first (so they always win), then prompt, then allow.
    Each rule becomes one `prefix_rule(...)`. Patterns containing `*` are
    skipped (Codex prefix_rule expects literal prefixes; we comment them).
    """
    out: list[str] = []
    out.append("# GENERATED BY agentic-os adapter compiler — do not edit by hand.")
    out.append("# Source: agent-os/policies/shell-policy.yaml")
    out.append("# Codex execpolicy DSL: prefix_rule(pattern=[...], decision=...).")
    out.append("# Valid decisions: allow | prompt | forbidden")
    out.append("")

    sections = (
        ("forbidden", policies.shell.forbidden, "forbidden"),
        ("prompt", policies.shell.prompt, "prompt"),
        ("allow", policies.shell.allow, "allow"),
    )
    for label, rules, decision in sections:
        out.append(f"# --- {label} rules ---")
        for rule in rules:
            pattern = rule["pattern"]
            reason = rule.get("reason", "")
            # Strip trailing "*" — Codex prefix_rule is a literal-prefix match.
            literal_prefix = list(pattern)
            had_glob_tail = False
            while literal_prefix and literal_prefix[-1] == "*":
                literal_prefix.pop()
                had_glob_tail = True
            # If the pattern contains any interior "*" we cannot express it as
            # a prefix_rule; emit as a comment so reviewers know it was skipped.
            if any(t == "*" for t in literal_prefix) or not literal_prefix:
                out.append(
                    f"# SKIPPED (non-prefix pattern): {pattern} reason={reason!r}"
                )
                continue
            if reason:
                out.append(f"# {reason}")
            line = (
                f"prefix_rule(pattern={_format_argv_literal(literal_prefix)}, "
                f"decision={json.dumps(decision)})"
            )
            if had_glob_tail:
                line += "  # trailing-* expanded to prefix match"
            out.append(line)
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def emit(
    out_root: Path,
    context_md: str,
    policies: Policies,
    adapter_cfg: Mapping,
) -> list[tuple[Path, bytes]]:
    files: list[tuple[Path, bytes]] = []
    files.append((out_root / adapter_cfg["context_filename"], context_md.encode("utf-8")))
    sub = out_root / adapter_cfg["output_subdir"]
    files.append((sub / adapter_cfg["config_filename"], _config_toml(adapter_cfg).encode("utf-8")))
    hooks_dir = sub / adapter_cfg["hooks_subdir"]
    seen: set[str] = set()
    for h in adapter_cfg.get("hooks", []):
        script = h["script"]
        if script in seen:
            continue
        seen.add(script)
        body = _HOOK_TEMPLATE.format(event=h["event"])
        files.append((hooks_dir / script, body.encode("utf-8")))
    rules_dir = sub / adapter_cfg["rules_subdir"]
    files.append((rules_dir / adapter_cfg["rules_filename"], _rules_file(policies).encode("utf-8")))
    return files
