"""Gemini per-CLI adapter emission.

Locked decision #9: Gemini deny mechanism is JSON ``{"decision":"deny"}`` on
exit 0; exit code 2 is reserved as an emergency hard block.

Produces:
    generated/GEMINI.md
    generated/gemini/settings.json
    generated/gemini/hooks/before_tool.py
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Mapping

from agentos_cli.core.policy import Policies

CLI_NAME = "gemini"

_HOOK_TEMPLATE = '''\
#!/usr/bin/env python3
"""GENERATED BY agentic-os adapter compiler — do not edit by hand.

CLI: gemini
Event: {event}

Gemini hook contract: read JSON from stdin, write JSON
``{{"decision":"allow"|"deny","reason":"..."}}`` to stdout, exit 0.
Exit code 2 is reserved as an emergency hard block.
"""
from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path

MAX_STDIN_BYTES = 1_000_000


def _audit(decision: str, reason: str, raw_len: int) -> None:
    try:
        root = os.environ.get("GEMINI_PROJECT_DIR") or os.getcwd()
        outdir = Path(root) / "agent-os" / "outputs" / "_global" / "temp"
        outdir.mkdir(parents=True, exist_ok=True)
        path = outdir / "hook-audit.jsonl"
        rec = {{
            "ts": time.time(),
            "cli": "gemini",
            "event": {event!r},
            "decision": decision,
            "reason": reason,
            "input_bytes": raw_len,
        }}
        with path.open("a", encoding="utf-8") as fh:
            fh.write(json.dumps(rec) + "\\n")
    except Exception:
        pass


def _emit(decision: str, reason: str, raw_len: int) -> int:
    payload = {{"decision": decision, "reason": reason}}
    try:
        sys.stdout.write(json.dumps(payload))
        sys.stdout.flush()
    except Exception:
        pass
    _audit(decision, reason, raw_len)
    return 0  # JSON deny on exit-0 per contract


def _deny(reason: str, raw_len: int = 0) -> int:
    return _emit("deny", reason, raw_len)


def _allow(reason: str, raw_len: int) -> int:
    return _emit("allow", reason, raw_len)


def _load_policies():
    try:
        root = os.environ.get("GEMINI_PROJECT_DIR") or os.getcwd()
        sys.path.insert(0, str(Path(root)))
        from agentos_cli.core.policy import load_policies  # type: ignore
        return load_policies(Path(root) / "agent-os" / "policies")
    except Exception:
        return None


def _evaluate(payload: dict, policies) -> tuple[str, str]:
    if policies is None:
        return "deny", "policy load failure (fail-closed)"
    tool = payload.get("tool_name") or payload.get("tool") or ""
    tinput = payload.get("tool_input") or payload.get("input") or {{}}
    if not isinstance(tinput, dict):
        return "deny", "tool_input is not an object"
    if tool in ("Shell", "Bash", "run_shell_command"):
        from agentos_cli.safety.shell_parse import parse_shell_string  # type: ignore
        from agentos_cli.core.policy import evaluate_shell  # type: ignore
        cmd = tinput.get("command")
        if isinstance(cmd, list) and all(isinstance(t, str) for t in cmd):
            argv = list(cmd)
        elif isinstance(cmd, str):
            argv = parse_shell_string(cmd)
            if argv is None:
                return "deny", "unsafe shell construct; route via approval"
        else:
            return "deny", "shell command must be string or list[str]"
        decision, rule = evaluate_shell(argv, policies)
        reason = (rule or {{}}).get("reason", "") if rule else ""
        if decision == "forbid":
            return "deny", f"shell forbid: {{reason}}"
        if decision == "prompt":
            return "deny", f"shell prompt (requires approval): {{reason}}"
        return "allow", "shell allow"
    if tool in ("write_file", "edit_file", "Write", "Edit"):
        from agentos_cli.core.policy import evaluate_file_write  # type: ignore
        path = tinput.get("file_path") or tinput.get("path")
        if not isinstance(path, str) or not path:
            return "deny", "file path missing"
        root = os.environ.get("GEMINI_PROJECT_DIR") or os.getcwd()
        decision, reason = evaluate_file_write(Path(path), Path(root), policies)
        if decision == "deny":
            return "deny", f"file write denied: {{reason}}"
        return "allow", "file write allow"
    return "allow", f"tool {{tool!r}} not policy-evaluated"


def main() -> int:
    raw_len = 0
    try:
        raw = sys.stdin.buffer.read(MAX_STDIN_BYTES + 1)
        raw_len = len(raw)
        if raw_len == 0:
            return _deny("empty stdin", raw_len)
        if raw_len > MAX_STDIN_BYTES:
            return _deny("stdin payload exceeds 1MB cap", raw_len)
        try:
            text = raw.decode("utf-8", errors="strict")
        except UnicodeDecodeError as e:
            return _deny(f"utf-8 decode failure: {{e.__class__.__name__}}", raw_len)
        try:
            payload = json.loads(text)
        except json.JSONDecodeError as e:
            return _deny(f"json parse failure: {{e.__class__.__name__}}", raw_len)
        if not isinstance(payload, dict):
            return _deny("payload must be a JSON object", raw_len)
        if any(k in payload for k in ("__proto__", "constructor", "prototype")):
            return _deny("disallowed reserved key in payload", raw_len)
        policies = _load_policies()
        decision, reason = _evaluate(payload, policies)
        if decision == "deny":
            return _deny(reason, raw_len)
        return _allow(reason, raw_len)
    except Exception as e:
        return _deny(f"unexpected: {{e.__class__.__name__}}", raw_len)


if __name__ == "__main__":
    sys.exit(main())
'''


def _settings_json(adapter_cfg: Mapping) -> str:
    grouped: dict[str, list[dict]] = {}
    for h in adapter_cfg.get("hooks", []):
        native = h["native_event"]
        cmd = f"python3 ./.gemini/hooks/{h['script']}"
        grouped.setdefault(native, []).append({"command": cmd})
    body = {"hooks": {k: grouped[k] for k in sorted(grouped)}}
    return json.dumps(body, indent=2, sort_keys=True) + "\n"


def emit(
    out_root: Path,
    context_md: str,
    policies: Policies,
    adapter_cfg: Mapping,
) -> list[tuple[Path, bytes]]:
    files: list[tuple[Path, bytes]] = []
    files.append((out_root / adapter_cfg["context_filename"], context_md.encode("utf-8")))
    sub = out_root / adapter_cfg["output_subdir"]
    files.append(
        (sub / adapter_cfg["settings_filename"], _settings_json(adapter_cfg).encode("utf-8"))
    )
    hooks_dir = sub / adapter_cfg["hooks_subdir"]
    seen: set[str] = set()
    for h in adapter_cfg.get("hooks", []):
        script = h["script"]
        if script in seen:
            continue
        seen.add(script)
        body = _HOOK_TEMPLATE.format(event=h["event"])
        files.append((hooks_dir / script, body.encode("utf-8")))
    return files
